name: Build HTML to APK
on:
  push:
    branches:
      - main

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Convert HTML to APK
        uses: kimhuilim/html-to-apk-action@v1
        with:
          build-folder-path: '.'
          app-name: 'InfoL'
