name: Build HTML to APK
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Siapkan folder web
        run: |
          mkdir www
          rsync -a --exclude='.git' --exclude='.github' --exclude='www' ./ www/

      - name: Install Capacitor
        run: |
          npm init -y
          npm i @capacitor/core @capacitor/cli @capacitor/android
          npx cap init InfoL com.farhan.infol --web-dir=www
          npx cap add android
          npx cap sync android

      - name: Perbaiki duplicate Kotlin
        run: |
          cat >> android/app/build.gradle << 'EOF'

          configurations.all {
              exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk7'
              exclude group: 'org.jetbrains.kotlin', module: 'kotlin-stdlib-jdk8'
          }
          EOF

      - name: Build APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: InfoL-apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
